#!/bin/bash
# (moves and) renames vychodil's sources and results
# 29. VI 2016

mv examples-vychodil/example01.heroc examples/vychodil01-hello-world.heroc
mv examples-vychodil/example01.txt examples/vychodil01-hello-world.txt
mv examples-vychodil/example02.heroc examples/vychodil02-fib-iter.heroc
mv examples-vychodil/example02.txt examples/vychodil02-fib-iter.txt
mv examples-vychodil/example04.txt examples/vychodil04-xor-swap.txt
mv examples-vychodil/example04.heroc examples/vychodil04-xor-swap.heroc
mv examples-vychodil/example15.heroc examples/vychodil15-fact-lin-ternary.heroc
mv examples-vychodil/example15.txt examples/vychodil15-fact-lin-ternary.txt
mv examples-vychodil/example03.heroc examples/vychodil03-ptr-swap.heroc
mv examples-vychodil/example03.txt examples/vychodil03-ptr-swap.txt
mv examples-vychodil/example05.txt examples/vychodil05-triangle-while.txt
mv examples-vychodil/example05.heroc examples/vychodil05-triangle-while.heroc
mv examples-vychodil/example06.heroc examples/vychodil06-triangle-for.heroc
mv examples-vychodil/example06.txt examples/vychodil06-triangle-for.txt
mv examples-vychodil/example07.txt examples/vychodil07-triangle-for-breaks.txt
mv examples-vychodil/example08.txt examples/vychodil08-triangle-while-breaks.txt
mv examples-vychodil/example08.heroc examples/vychodil08-triangle-while-breaks.heroc 
mv examples-vychodil/example07.heroc examples/vychodil07-triangle-for-breaks.heroc
mv examples-vychodil/example09.txt examples/vychodil09-triangle-do.txt
mv examples-vychodil/example09.heroc examples/vychodil09-triangle-do.heroc
mv examples-vychodil/example10.heroc examples/vychodil10-triangle-blanks.heroc
mv examples-vychodil/example10.txt examples/vychodil10-triangle-blanks.txt
mv examples-vychodil/example11.txt examples/vychodil11-unary-minus.txt
mv examples-vychodil/example11.heroc examples/vychodil11-unary-minus.heroc
mv examples-vychodil/example12.heroc examples/vychodil12-call-chaining.heroc
mv examples-vychodil/example12.txt examples/vychodil12-call-chaining.txt
mv examples-vychodil/example13.txt examples/vychodil13-fact-lin-rec.txt
mv examples-vychodil/example13.heroc examples/vychodil13-fact-lin-rec.heroc
mv examples-vychodil/example14.heroc examples/vychodil14-fact-lin-rec-ternary.heroc
mv examples-vychodil/example14.txt examples/vychodil14-fact-lin-rec-ternary.txt
mv examples-vychodil/example15.txt examples/vychodil15-fact-tail-rec.txt
mv examples-vychodil/example16.txt examples/vychodil16-fact-tail-rec.txt
mv examples-vychodil/example16.heroc examples/vychodil16-fact-tail-rec.heroc
mv examples-vychodil/example17.heroc examples/vychodil17-fact-tail-rec-ptr.heroc
mv examples-vychodil/example17.txt examples/vychodil17-fact-tail-rec-ptr.txt
mv examples-vychodil/example18.txt examples/vychodil18-fact-tail-rec-ptr-local.txt
mv examples-vychodil/example18.heroc examples/vychodil18-fact-tail-rec-ptr-local.heroc
mv examples-vychodil/example19.heroc examples/vychodil19-fib-tree-rec.heroc
mv examples-vychodil/example20.heroc examples/vychodil20-fib-tree-rec-graph.heroc
mv examples-vychodil/example19.txt examples/vychodil19-fib-tree-rec.txt
mv examples-vychodil/example20.txt examples/vychodil20-fib-tree-rec-graph.txt
mv examples-vychodil/example21.txt examples/vychodil21-arrays.txt
mv examples-vychodil/example21.heroc examples/vychodil21-arrays.heroc
mv examples-vychodil/example22.heroc examples/vychodil22-arrays-lalloc.heroc
mv examples-vychodil/example22.txt examples/vychodil22-arrays-lalloc.txt
mv examples-vychodil/example23.txt examples/vychodil23-scheme-lists.txt
mv examples-vychodil/example23.heroc examples/vychodil23-scheme-lists.heroc
mv examples-vychodil/example24.heroc examples/vychodil24-scheme-lists-2.heroc
mv examples-vychodil/example24.txt examples/vychodil24-scheme-lists-2.txt
mv examples-vychodil/example25.txt examples/vychodil25-scheme-lists-print.txt
mv examples-vychodil/example25.heroc examples/vychodil25-scheme-lists-print.heroc
mv examples-vychodil/example26.heroc examples/vychodil26-scheme-lists-more.heroc
mv examples-vychodil/example26.txt examples/vychodil26-scheme-lists-more.txt
mv examples-vychodil/example27.txt examples/vychodil27-buble-sort.txt
mv examples-vychodil/example27.txt examples/vychodil27-buble-sort.heroc
mv examples-vychodil/example27.heroc examples/vychodil27-buble-sort.heroc
mv examples-vychodil/example28.heroc examples/vychodil28-quick-sort.heroc
mv examples-vychodil/example28.txt examples/vychodil28-quick-sort.txt
mv examples-vychodil/example29.txt examples/vychodil29-arithmetic-relational.txt
mv examples-vychodil/example29.heroc examples/vychodil29-arithmetic-relational.heroc
mv examples-vychodil/example30.heroc examples/vychodil30-arithm-logic-bitwise.heroc
mv examples-vychodil/example30.txt examples/vychodil30-arithm-logic-bitwise.txt
mv examples-vychodil/example31.txt examples/vychodil31-assignment.txt
mv examples-vychodil/example31.heroc examples/vychodil31-assignment.heroc
mv examples-vychodil/example32.heroc examples/vychodil32-ternar.heroc
mv examples-vychodil/example32.txt examples/vychodil32-ternar.txt
mv examples-vychodil/example33.txt examples/vychodil33-maze.txt
mv examples-vychodil/example33.heroc examples/vychodil33-maze.heroc
mv examples-vychodil/example34.heroc examples/vychodil34-refer-derefer.heroc
mv examples-vychodil/example34.txt examples/vychodil34-refer-derefer.txt
mv examples-vychodil/example35.txt examples/vychodil35-var-scope.txt
mv examples-vychodil/example35.heroc examples/vychodil35-var-scope.heroc
mv examples-vychodil/example36.heroc examples/vychodil36-global-local-araay.heroc
mv examples-vychodil/example36.txt examples/vychodil36-global-local-araay.txt
mv examples-vychodil/example37.txt examples/vychodil37-extras-strings.txt
mv examples-vychodil/example37.heroc examples/vychodil37-extras-strings.heroc
mv examples-vychodil/example38.heroc examples/vychodil38-extras-array-expr.heroc
mv examples-vychodil/example38.txt examples/vychodil38-extras-array-expr.txt
mv examples-vychodil/example39.txt examples/vychodil39-simple-stackmachine.txt
mv examples-vychodil/example39.heroc examples/vychodil39-simple-stackmachine.heroc
mv examples-vychodil/example40.heroc examples/vychodil40-array-permutations.heroc
mv examples-vychodil/example40.txt examples/vychodil40-array-permutations.txt

